# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: nuruyaxo2561
# "service" is the name of this project. This will also be added to your AWS resource names.
service: M365-Renew-AWS

provider:
  name: aws
  runtime: nodejs20.x

functions:
  rateHandler:
    handler: handler.run
    events:
      - schedule: rate(1 minute)
